config:
  credentials:
  - id: https://github.com/PalomoIFCA/private4
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private4:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/private4
      repo: https://github.com/PalomoIFCA/private4
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private4 git:
        commands:
        - /usr/bin/env sh .sqa/script.ochre_apprehensive_clownfish.sh
        container: qc.acc_rust_happy_fox
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private4 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.copper_wise_kingfisher.sh
        container: qc.doc_cayenne_wondrous_gorilla
      github.com/PalomoIFCA/private4 git:
        commands:
        - /usr/bin/env sh .sqa/script.marigold_productive_ferret.sh
        container: qc.doc_caramel_carefree_wolf
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private4 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tangerine_fierce_crocodile.sh
        container: qc.lic_mulberry_articulate_goat
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private4 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.butterscotch_worried_leopard.sh
        container: qc.sec_gamboge_cranky_alpaca
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private4 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scarlet_harmonious_crocodile.sh
        container: qc.sty_peach_positive_eel
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private4 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sand_tolerant_cobra.sh
        container: qc.uni_ebony_content_whale
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private4 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cinnamon_productive_manta.sh
        container: qc.ver_emerald_logical_camel
timeout: 5400
