config:
  credentials:
  - id: https://github.com/PalomoIFCA/private4
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private4:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/private4
      repo: https://github.com/PalomoIFCA/private4
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private4 git:
        commands:
        - /usr/bin/env sh .sqa/script.thunder_determined_dolphin.sh
        container: qc.acc_cinnabar_insightful_skunk
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private4 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cerise_grumpy_rattlesnake.sh
        container: qc.doc_wisteria_brilliant_kraken
      github.com/PalomoIFCA/private4 git:
        commands:
        - /usr/bin/env sh .sqa/script.jet_rustic_orangutan.sh
        container: qc.doc_chocolate_visionary_tortoise
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private4 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dusk_impulsive_thrush.sh
        container: qc.lic_pumpkin_shrewd_cassowary
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private4 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bluebell_tactful_giraffe.sh
        container: qc.sec_cherry_patient_python
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private4 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lapis_sympathetic_tiger.sh
        container: qc.sty_chili_happy_skunk
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private4 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.jasmine_optimistic_griffin.sh
        container: qc.uni_kiwi_outgoing_narwhal
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private4 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.orange_anxious_hippopotamus.sh
        container: qc.ver_dawn_inventive_lobster
timeout: 5400
