config:
  credentials:
  - id: https://github.com/PalomoIFCA/private4
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private4:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/private4
      repo: https://github.com/PalomoIFCA/private4
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private4 git:
        commands:
        - /usr/bin/env sh .sqa/script.ochre_candid_termite.sh
        container: qc.acc_beige_patient_walrus
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private4 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scarlet_warm_cobra.sh
        container: qc.doc_walnut_humorous_spider
      github.com/PalomoIFCA/private4 git:
        commands:
        - /usr/bin/env sh .sqa/script.gunmetal_devoted_iguana.sh
        container: qc.doc_salmon_organized_boa
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private4 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.puce_vigilant_sparrow.sh
        container: qc.lic_puce_silly_peacock
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private4 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wine_agile_griffin.sh
        container: qc.sec_sepia_smart_sloth
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private4 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.aqua_focused_macaw.sh
        container: qc.sty_byzantium_mischievous_manta
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private4 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.orange_productive_squirrel.sh
        container: qc.uni_claret_lively_ostrich
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private4 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sepia_artistic_turtle.sh
        container: qc.ver_tide_dreamy_capybara
timeout: 5400
